version: '3.7'

services:

 facturacion:
   build:
     context: ./services/facturacion
     dockerfile: Dockerfile-dev
   volumes:
     - './services/facturacion:/fact/src/app'
   ports:
     - 5001:5000
   environment:
     - FLASK_APP=project/__init__.py
     - FLASK_ENV=development
