version: '3.7'

services:

 facturacion:
   build:
     context: ./services/facturacion
     dockerfile: Dockerfile-dev
   volumes:
     - './services/facturacion:/fact/src/app'
   ports:
     - 5001:5000
   environment:
     - FLASK_APP=project/__init__.py
     - FLASK_ENV=development
     - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
     - DATABASE_URL=postgres://postgres:postgres@facturacion-db:5432/facturacion_dev  # nuevo
     - DATABASE_TEST_URL=postgres://postgres:postgres@facturacion-db:5432/facturacion_test  # nuevo
   depends_on : # nuevo 
     - facturacion-db


 facturacion-db:  # nuevo
   build:
     context: ./services/facturacion/project/db
     dockerfile: Dockerfile
   ports:
     - 5435:5432
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
